/* =====================================
 * Generated by Mod-c 0.26.3
 * HEADER test2_export_struct PROGRAM
 * ===================================== */

#ifndef MODC_PROGRAM_test2_export_struct_H
#define MODC_PROGRAM_test2_export_struct_H

/* === TYPE EXPORT === */
typedef struct TName TName;
typedef struct TName {
    string first_name;
    string last_name;
} TName;

#endif /* MODC_PROGRAM_test2_export_struct_H */
