/* =====================================
 * Generated by Mod-c 0.22.1
 * HEADER PrimeSieve PROGRAM
 * ===================================== */

#ifndef MODC_PROGRAM_PrimeSieve_H
#define MODC_PROGRAM_PrimeSieve_H

/* === IMPORT === */
#include "utils.h"

#endif /* MODC_PROGRAM_PrimeSieve_H */
