/* =====================================
 * Generated by Mod-c 0.26.8
 * MODULE Tsds
 * ===================================== */

#include "Tsds.h"

void Tsds(void);

#include "stdio.h"
#include "stdlib.h"
#include "string.h"
#include "ctype.h"
#include "limits.h"
#include "stddef.h"
#include "sys/types.h"
#include "stdarg.h"
#include "stdint.h"
#define s_malloc malloc
#define s_realloc realloc
#define s_free free
#define SDS_MAX_PREALLOC (1024*1024)
static const char* SDS_NOINIT = "SDS_NOINIT";
#define SDS_TYPE_5  0
#define SDS_TYPE_8  1
#define SDS_TYPE_16 2
#define SDS_TYPE_32 3
#define SDS_TYPE_64 4
#define SDS_TYPE_MASK 7
#define SDS_TYPE_BITS 3
#define SDS_HDR_VAR(T, s) struct sdshdr##T *sh = (void*)((s)-(sizeof(struct sdshdr##T)));
#define SDS_HDR(T, s) ((struct sdshdr##T *)((s)-(sizeof(struct sdshdr##T))))
#define SDS_TYPE_5_LEN(f) ((f)>>SDS_TYPE_BITS)
#define SDS_HDR_SH(T, s) (void*)((s)-(sizeof(struct sdshdr##T)))
/**
 * Return length of s
 */
size_t sdslen(sds s)
{
    uchar flags = s[-1];
    switch ((flags & SDS_TYPE_MASK))
    {
        case SDS_TYPE_5:
        {
            /* return value captured before defers */
            size_t __ret_l178 = SDS_TYPE_5_LEN(flags);
            return __ret_l178;
        }
        break;
        case SDS_TYPE_8:
        {
            sdshdr8* sh_l180_c19 = (sdshdr8*)(s - ((integer)sizeof(sdshdr8)));
            /* return value captured before defers */
            size_t __ret_l181 = (*(sh_l180_c19)).length;
            return __ret_l181;
        }
        break;
        case SDS_TYPE_16:
        {
            sdshdr16* sh_l183_c19 = (sdshdr16*)(s - ((integer)sizeof(sdshdr16)));
            /* return value captured before defers */
            size_t __ret_l184 = (*(sh_l183_c19)).length;
            return __ret_l184;
        }
        break;
        case SDS_TYPE_32:
        {
            sdshdr32* sh_l186_c19 = (sdshdr32*)(s - ((integer)sizeof(sdshdr32)));
            /* return value captured before defers */
            size_t __ret_l187 = (*(sh_l186_c19)).length;
            return __ret_l187;
        }
        break;
        case SDS_TYPE_64:
        {
            sdshdr64* sh_l189_c19 = (sdshdr64*)(s - ((integer)sizeof(sdshdr64)));
            /* return value captured before defers */
            size_t __ret_l190 = (*(sh_l189_c19)).length;
            return __ret_l190;
        }
        break;
        default:
        {
            /* return value captured before defers */
            size_t __ret_l192 = 0;
            return __ret_l192;
        }
        break;
    }
}

/**
 * Return available space
 */
size_t sdsavail(sds s)
{
    uchar flags = s[-1];
    switch ((flags & SDS_TYPE_MASK))
    {
        case SDS_TYPE_5:
        {
            /* return value captured before defers */
            size_t __ret_l205 = 0;
            return __ret_l205;
        }
        break;
        case SDS_TYPE_8:
        {
            sdshdr8* sh_l207_c19 = (sdshdr8*)(s - ((integer)sizeof(sdshdr8)));
            /* return value captured before defers */
            size_t __ret_l208 = (*(sh_l207_c19)).alloc - (*(sh_l207_c19)).length;
            return __ret_l208;
        }
        break;
        case SDS_TYPE_16:
        {
            sdshdr16* sh_l210_c19 = (sdshdr16*)(s - ((integer)sizeof(sdshdr16)));
            /* return value captured before defers */
            size_t __ret_l211 = (*(sh_l210_c19)).alloc - (*(sh_l210_c19)).length;
            return __ret_l211;
        }
        break;
        case SDS_TYPE_32:
        {
            sdshdr32* sh_l213_c19 = (sdshdr32*)(s - ((integer)sizeof(sdshdr32)));
            /* return value captured before defers */
            size_t __ret_l214 = (*(sh_l213_c19)).alloc - (*(sh_l213_c19)).length;
            return __ret_l214;
        }
        break;
        case SDS_TYPE_64:
        {
            sdshdr64* sh_l216_c19 = (sdshdr64*)(s - ((integer)sizeof(sdshdr64)));
            /* return value captured before defers */
            size_t __ret_l217 = (*(sh_l216_c19)).alloc - (*(sh_l216_c19)).length;
            return __ret_l217;
        }
        break;
        default:
        {
            /* return value captured before defers */
            size_t __ret_l219 = 0;
            return __ret_l219;
        }
        break;
    }
}

/**
 * Set length of s to newlen
 */
void sdssetlen(sds s, size_t newlen)
{
    uchar flags = s[-1];
    switch ((flags & SDS_TYPE_MASK))
    {
        case SDS_TYPE_5:
        {
            uchar* fp = ((uchar*)s) - 1;
            (*fp) = SDS_TYPE_5 | (newlen << SDS_TYPE_BITS);
        }
        break;
        case SDS_TYPE_8:
        {
            ((*SDS_HDR(8, s))).length = newlen;
        }
        break;
        case SDS_TYPE_16:
        {
            ((*SDS_HDR(16, s))).length = newlen;
        }
        break;
        case SDS_TYPE_32:
        {
            ((*SDS_HDR(32, s))).length = newlen;
        }
        break;
        case SDS_TYPE_64:
        {
            ((*SDS_HDR(64, s))).length = newlen;
        }
        break;
        default:
        {
        }
        break;
    }
}

/**
 * Increase length by inc
 */
void sdsinclen(sds s, size_t inc_)
{
    uchar flags = s[-1];
    switch ((flags & SDS_TYPE_MASK))
    {
        case SDS_TYPE_5:
        {
            uchar* fp = ((uchar*)s) - 1;
            uchar newlen = SDS_TYPE_5_LEN(flags) + inc_;
            (*fp) = SDS_TYPE_5 | (newlen << SDS_TYPE_BITS);
        }
        break;
        case SDS_TYPE_8:
        {
            ((*SDS_HDR(8, s))).length += inc_;
        }
        break;
        case SDS_TYPE_16:
        {
            ((*SDS_HDR(16, s))).length += inc_;
        }
        break;
        case SDS_TYPE_32:
        {
            ((*SDS_HDR(32, s))).length += inc_;
        }
        break;
        case SDS_TYPE_64:
        {
            ((*SDS_HDR(64, s))).length += inc_;
        }
        break;
        default:
        {
        }
        break;
    }
}

/**
 * sdsalloc() = sdsavail() + sdslen()
 */
size_t sdsalloc(const sds s)
{
    uchar flags = s[-1];
    switch ((flags & SDS_TYPE_MASK))
    {
        case SDS_TYPE_5:
        {
            /* return value captured before defers */
            size_t __ret_l291 = SDS_TYPE_5_LEN(flags);
            return __ret_l291;
        }
        break;
        case SDS_TYPE_8:
        {
            /* return value captured before defers */
            size_t __ret_l293 = ((*SDS_HDR(8, s))).alloc;
            return __ret_l293;
        }
        break;
        case SDS_TYPE_16:
        {
            /* return value captured before defers */
            size_t __ret_l295 = ((*SDS_HDR(16, s))).alloc;
            return __ret_l295;
        }
        break;
        case SDS_TYPE_32:
        {
            /* return value captured before defers */
            size_t __ret_l297 = ((*SDS_HDR(32, s))).alloc;
            return __ret_l297;
        }
        break;
        case SDS_TYPE_64:
        {
            /* return value captured before defers */
            size_t __ret_l299 = ((*SDS_HDR(64, s))).alloc;
            return __ret_l299;
        }
        break;
        default:
        {
            /* return value captured before defers */
            size_t __ret_l301 = 0;
            return __ret_l301;
        }
        break;
    }
}

/**
 * Set alloc to newlen
 */
void sdssetalloc(sds s, size_t newlen)
{
    uchar flags = {0};
    if (s != nil)
    {
        flags = s[-1];
        switch ((flags & SDS_TYPE_MASK))
        {
            case SDS_TYPE_5:
            {
            }
            break;
            case SDS_TYPE_8:
            {
                ((*SDS_HDR(8, s))).alloc = newlen;
            }
            break;
            case SDS_TYPE_16:
            {
                ((*SDS_HDR(16, s))).alloc = newlen;
            }
            break;
            case SDS_TYPE_32:
            {
                ((*SDS_HDR(32, s))).alloc = newlen;
            }
            break;
            case SDS_TYPE_64:
            {
                ((*SDS_HDR(64, s))).alloc = newlen;
            }
            break;
            default:
            {
            }
            break;
        }
    }
}

sds sdsnewlen(const VOID* init, size_t initlen);
sds sdsnew(const char* init);
sds sdsempty(void);
sds sdsdup(const sds s);
void sdsfree(sds s);
sds sdsgrowzero(sds s, size_t length);
sds sdscatlen(sds s, const VOID* t, size_t length);
sds sdscat(sds s, const char* t);
sds sdscatsds(sds s, const sds t);
sds sdscpylen(sds s, const char* t, size_t length);
sds sdscpy(sds s, const char* t);
sds sdscatvprintf(sds s, const char* fmt, va_list ap);
sds sdscatprintf(sds s, const char* fmt, ...);
sds sdscatfmt(sds s, const char* fmt, ...);
sds sdstrim(sds s, const char* cset);
void sdsrange(sds s, ssize_t start, ssize_t end_);
void sdsupdatelen(sds s);
void sdsclear(sds s);
int sdscmp(const sds s1, const sds s2);
sds* sdssplitlen(const char* s, ssize_t length, const char* sep, int seplen, int* count);
void sdsfreesplitres(sds* tokens, int count);
void sdstolower(sds s);
void sdstoupper(sds s);
sds sdsfromlonglong(llong value);
sds sdscatrepr(sds s, const char* p, size_t length);
sds* sdssplitargs(const char* line, int* argc);
sds sdsmapchars(sds s, const char* from_, const char* to_, size_t setlen);
sds sdsjoin(char** argv, int argc, char* sep);
sds sdsjoinsds(sds* argv, int argc, const char* sep, size_t seplen);
sds sdsMakeRoomFor(sds s, size_t addlen);
void sdsIncrLen(sds s, ssize_t incr);
sds sdsRemoveFreeSpace(sds s);
size_t sdsAllocSize(sds s);
VOID* sdsAllocPtr(sds s);
VOID* sds_malloc(size_t size);
VOID* sds_realloc(VOID* ptr, size_t size);
void sds_free(VOID* ptr);
#ifdef REDIS_TEST
int sdsTest(int argc, char** argv);
#endif
static int sdsHdrSize(char hdr_type)
{
    switch (hdr_type & SDS_TYPE_MASK)
    {
        case SDS_TYPE_5:
        {
            /* return value captured before defers */
            int __ret_l405 = ((integer)sizeof(sdshdr5));
            return __ret_l405;
        }
        break;
        case SDS_TYPE_8:
        {
            /* return value captured before defers */
            int __ret_l407 = ((integer)sizeof(sdshdr8));
            return __ret_l407;
        }
        break;
        case SDS_TYPE_16:
        {
            /* return value captured before defers */
            int __ret_l409 = ((integer)sizeof(sdshdr16));
            return __ret_l409;
        }
        break;
        case SDS_TYPE_32:
        {
            /* return value captured before defers */
            int __ret_l411 = ((integer)sizeof(sdshdr32));
            return __ret_l411;
        }
        break;
        case SDS_TYPE_64:
        {
            /* return value captured before defers */
            int __ret_l413 = ((integer)sizeof(sdshdr64));
            return __ret_l413;
        }
        break;
        default:
        {
            /* return value captured before defers */
            int __ret_l415 = 0;
            return __ret_l415;
        }
        break;
    }
}

static char sdsReqType(size_t string_size)
{
    if (string_size < 1 << 5)
    {
        /* return value captured before defers */
        char __ret_l426 = SDS_TYPE_5;
        return __ret_l426;
    }
    else if (string_size < 1 << 8)
    {
        /* return value captured before defers */
        char __ret_l428 = SDS_TYPE_8;
        return __ret_l428;
    }
    else if (string_size < 1 << 16)
    {
        /* return value captured before defers */
        char __ret_l430 = SDS_TYPE_16;
        return __ret_l430;
    }
    #if (LONG_MAX == LLONG_MAX)
    if (string_size < 1ll << 32)
    {
        /* return value captured before defers */
        char __ret_l435 = SDS_TYPE_32;
        return __ret_l435;
    }
    else
    {
        /* return value captured before defers */
        char __ret_l437 = SDS_TYPE_64;
        return __ret_l437;
    }
    #endif
    /* return value captured before defers */
    char __ret_l441 = SDS_TYPE_32;
    return __ret_l441;
}

/**
 * Create a new sds string with the content specified by the 'init' pointer
 * and 'initlen'.
 * If NIL is used for 'ini' the string is initialized with zero bytes.
 * If SDs_NOINIT is used, the buffer is left uninitialized;
 *
 * The string is always null-terminated (all the sds strings are, always) so
 * even if you create an sds string with:
 *
 * mystring := sdsnewlne("abc", 3)
 *
 * You can print the string with printf() as there is an implicit \0 at the
 * end of the string. However the string is binary safe and can contain
 * \0 characters in the middle, as the length is stored in the sds header.
 */
sds sdsnewlen(const VOID* init_to, size_t initlen)
{
    VOID* sh = {0};
    sds s = {0};
    char sds_type = sdsReqType(initlen);
    int hdrlen = 0;
    uchar* fp = {0};
    const VOID* init = init_to;
    if (sds_type == SDS_TYPE_5 && initlen == 0)
    {
        sds_type = SDS_TYPE_8;
    }
    hdrlen = sdsHdrSize(sds_type);
    sh = s_malloc(hdrlen + initlen + 1);
    if (sh == nil)
    {
        /* return value captured before defers */
        sds __ret_l481 = nil;
        return __ret_l481;
    }
    if (init == (const VOID*)SDS_NOINIT)
    {
        init = nil;
    }
    else if (!init)
    {
        memset(sh, 0, hdrlen + initlen + 1);
    }
    s = ((char*)sh) + hdrlen;
    fp = (uchar*)(s - 1);
    switch (sds_type)
    {
        case SDS_TYPE_5:
        {
            (*fp) = sds_type | (initlen << SDS_TYPE_BITS);
        }
        break;
        case SDS_TYPE_8:
        {
            sdshdr8* sh_l495_c19 = (sdshdr8*)(s - ((integer)sizeof(sdshdr8)));
            (*(sh_l495_c19)).length = initlen;
            (*(sh_l495_c19)).alloc = initlen;
            (*fp) = sds_type;
        }
        break;
        case SDS_TYPE_16:
        {
            sdshdr16* sh_l501_c19 = (sdshdr16*)(s - ((integer)sizeof(sdshdr16)));
            (*(sh_l501_c19)).length = initlen;
            (*(sh_l501_c19)).alloc = initlen;
            (*fp) = sds_type;
        }
        break;
        case SDS_TYPE_32:
        {
            sdshdr32* sh_l507_c19 = (sdshdr32*)(s - ((integer)sizeof(sdshdr32)));
            (*(sh_l507_c19)).length = initlen;
            (*(sh_l507_c19)).alloc = initlen;
            (*fp) = sds_type;
        }
        break;
        case SDS_TYPE_64:
        {
            sdshdr64* sh_l513_c19 = (sdshdr64*)(s - ((integer)sizeof(sdshdr64)));
            (*(sh_l513_c19)).length = initlen;
            (*(sh_l513_c19)).alloc = initlen;
            (*fp) = sds_type;
        }
        break;
        default:
        {
        }
        break;
    }
    if (initlen && init)
    {
        memcpy(s, init, initlen);
    }
    s[initlen] = '\0';
    /* return value captured before defers */
    sds __ret_l525 = s;
    return __ret_l525;
}

/**
 * Create an empty (zero length) sds string. Even in this case the string
 * always has an implicit nil term.
 */
sds sdsempty(void)
{
    /* return value captured before defers */
    sds __ret_l535 = sdsnewlen("", 0);
    return __ret_l535;
}

/**
 * Create a new sds string starting from a null terminaed C string.
 */
sds sdsnew(const char* init)
{
    size_t initlen = ((init == nil) ? 0 : strlen(init));
    /* return value captured before defers */
    sds __ret_l545 = sdsnewlen(init, initlen);
    return __ret_l545;
}

/**
 * Duplicate an sds string. 
 */
sds sdsdup(const sds s)
{
    /* return value captured before defers */
    sds __ret_l554 = sdsnewlen(s, sdslen(s));
    return __ret_l554;
}

/**
 * Free an sds string. No operation is performed if 's' is NIL.
 */
void sdsfree(sds s)
{
    if (s != nil)
    {
        s_free((char*)(s - sdsHdrSize(s[-1])));
    }
}

/**
 * Set the sds string length to the length as obtained with strlen(), so
 * considering as content only up to the first null term character.
 *
 * This function is useful when the sds string is hacked manually in some
 * way, like in the following example:
 *
 *  s := sdsnew("foobar")
 *  s[2] := '\0'
 *  sdsupdatelen(s)
 *  printf("%d\n", sdslen(s))
 *
 * The output will be "2", but if we comment out the call to sdsupdatelen()
 * the output will be "6" as the string was modified but the logical length
 * remains 6 bytes.
 */
void sdsupdatelen(sds s)
{
    size_t reallen = strlen(s);
    sdssetlen(s, reallen);
}

/**
 * Modify an ses string in-place to make it empty (zero length).
 * However all the existing buffer is not discarded but set as free space
 * so that next append operations will not require allocations up to the
 * number of bytes previously available.
 */
void sdsclear(sds s)
{
    sdssetlen(s, 0);
    s[0] = '\0';
}

/**
 * Enlarge the free space at the end of the sds string so that the caller
 * is sure that after calling this function can overwrite up to addlen
 * bytes after the end of the string, plus one more byte for null term.
 *
 * Note: this does not change the *length* of the sds string as returned
 * by sdslen(), but only the free buffer space we have.
 */
sds sdsMakeRoomFor(sds s, size_t addlen)
{
    VOID* sh = {0};
    VOID* newsh = {0};
    size_t avail = sdsavail(s);
    size_t length = {0};
    size_t newlen = {0};
    size_t reqlen = {0};
    char sds_type = {0};
    char oldtype = {0};
    int hdrlen = {0};
    sds new_s = nil;
    oldtype = s[-1] & SDS_TYPE_MASK;
    if (avail >= addlen)
    {
        /* return value captured before defers */
        sds __ret_l626 = s;
        return __ret_l626;
    }
    length = sdslen(s);
    sh = (char*)(s - sdsHdrSize(oldtype));
    newlen = length + addlen;
    reqlen = newlen;
    if (newlen < SDS_MAX_PREALLOC)
    {
        newlen *= 2;
    }
    else
    {
        newlen += SDS_MAX_PREALLOC;
    }
    sds_type = sdsReqType(newlen);
    if (sds_type == SDS_TYPE_5)
    {
        sds_type = SDS_TYPE_8;
    }
    hdrlen = sdsHdrSize(sds_type);
    assert((hdrlen + newlen + 1 > reqlen)); /* "Catch size_t overflow" */
    if (oldtype == sds_type)
    {
        newsh = s_realloc(sh, hdrlen + newlen + 1);
        if (newsh == nil)
        {
            /* return value captured before defers */
            sds __ret_l652 = nil;
            return __ret_l652;
        }
        new_s = (char*)newsh + hdrlen;
    }
    else
    {
        newsh = s_malloc(hdrlen + newlen + 1);
        if (newsh == nil)
        {
            /* return value captured before defers */
            sds __ret_l660 = nil;
            return __ret_l660;
        }
        memcpy((char*)newsh + hdrlen, s, length + 1);
        s_free(sh);
        new_s = (char*)newsh + hdrlen;
        new_s[-1] = sds_type;
        sdssetlen(new_s, length);
    }
    sdssetalloc(new_s, newlen);
    /* return value captured before defers */
    sds __ret_l669 = new_s;
    return __ret_l669;
}

/**
 * Reallocate the sds string so that it has no free space at the end. The
 * contained string remains not altered, but next concatenation operations
 * will require a reallocation.
 *
 * After the call, the passed sds string is no longer valid and all the
 * references must be substituted with the new pointer returned by the call.
 */
sds sdsRemoveFreeSpace(sds s)
{
    VOID* sh = {0};
    VOID* newsh = {0};
    char sds_type = {0};
    char oldtype = {0};
    int hdrlen = {0};
    int oldhdrlen = {0};
    size_t length = sdslen(s);
    size_t avail = sdsavail(s);
    sds new_s = nil;
    oldtype = s[-1] & SDS_TYPE_MASK;
    oldhdrlen = sdsHdrSize(oldtype);
    sh = (char*)(s - oldhdrlen);
    if (avail == 0)
    {
        /* return value captured before defers */
        sds __ret_l697 = s;
        return __ret_l697;
    }
    sds_type = sdsReqType(length);
    hdrlen = sdsHdrSize(sds_type);
    if (oldtype == sds_type || sds_type > SDS_TYPE_8)
    {
        newsh = s_realloc(sh, oldhdrlen + length + 1);
        if (newsh == nil)
        {
            /* return value captured before defers */
            sds __ret_l712 = nil;
            return __ret_l712;
        }
        new_s = (char*)newsh + oldhdrlen;
    }
    else
    {
        newsh = s_malloc(hdrlen + length + 1);
        if (newsh == nil)
        {
            /* return value captured before defers */
            sds __ret_l718 = nil;
            return __ret_l718;
        }
        memcpy((char*)newsh + hdrlen, s, length + 1);
        s_free(sh);
        new_s = (char*)newsh + hdrlen;
        new_s[-1] = sds_type;
        sdssetlen(new_s, length);
    }
    sdssetalloc(new_s, length);
    /* return value captured before defers */
    sds __ret_l727 = new_s;
    return __ret_l727;
}

/**
 * Return the total size of the allocation of the specified sds string,
 * including:
 *  1) The sds header before the pointer.
 *  2) The string.
 *  3) The free buffer at the end if any.
 *  4) The implicit null term.
 */
size_t sdsAllocSize(sds s)
{
    size_t alloc = sdsalloc(s);
    /* return value captured before defers */
    size_t __ret_l742 = sdsHdrSize(s[-1] + alloc + 1);
    return __ret_l742;
}

/**
 * Return the pointer of the actual SDS allocation (normally SDS strings
 * are referenced by the start of the string buffer).
 */
VOID* sdsAllocPtr(sds s)
{
    /* return value captured before defers */
    VOID* __ret_l752 = (VOID*)(s - sdsHdrSize(s[-1]));
    return __ret_l752;
}

/**
 * Increment the sds length and decrements the left free space at the 
 * end of the string according to 'incr'. Also set the null term
 * in the new end of the string.
 *
 * This function is used in order to fix the string length after the
 * user calls sdsMakeRoomFor(), writes something after the end of
 * the current string, and finally needs to set the new length.
 *
 * Note: it is possible to use a negative increment in order to 
 * right-trim the string.
 *
 * Usage example:
 *
 * Using sdsIncrLen() and sdsMakeRoomFor() it is possible to mount the
 * following schema, to cat bytes coming from the kernel to the end of an
 * sds string without copying into an intermediate buffer:
 *
 * oldlen := sdslen(s)
 * s := sdsMakeRoomFor(s, BUFFER_SIZE)
 * nread := read(fd, s+oldlen, BUFFER_SIZE)
 * ... check for nread <= 0 and handle it...
 * sdsIncrLen(s, nread)
 */
void sdsIncrLen(sds s, ssize_t incr)
{
    uchar flags = s[-1];
    size_t length = {0};
    switch (flags & SDS_TYPE_MASK)
    {
        case SDS_TYPE_5:
        {
            uchar* fp = (uchar*)s - 1;
            uchar oldlen = SDS_TYPE_5_LEN(flags);
            assert(((incr > 0 && oldlen + incr < 32) || (incr < 0 && oldlen >= (uint)-incr)));
            (*fp) = SDS_TYPE_5 | ((oldlen + incr) << SDS_TYPE_BITS);
            length = oldlen + incr;
        }
        break;
        case SDS_TYPE_8:
        {
            sdshdr8* sh_l796_c19 = (sdshdr8*)(s - ((integer)sizeof(sdshdr8)));
            assert(((incr >= 0 && (*(sh_l796_c19)).alloc - (*(sh_l796_c19)).length >= incr) || (incr < 0 && (*(sh_l796_c19)).length >= (uint)-incr)));
            (*(sh_l796_c19)).length += incr;
            length = (*(sh_l796_c19)).length;
        }
        break;
        case SDS_TYPE_16:
        {
            sdshdr16* sh_l803_c19 = (sdshdr16*)(s - ((integer)sizeof(sdshdr16)));
            assert(((incr >= 0 && (*(sh_l803_c19)).alloc - (*(sh_l803_c19)).length >= incr) || (incr < 0 && (*(sh_l803_c19)).length >= (uint)-incr)));
            (*(sh_l803_c19)).length += incr;
            length = (*(sh_l803_c19)).length;
        }
        break;
        case SDS_TYPE_32:
        {
            sdshdr32* sh_l810_c19 = (sdshdr32*)(s - ((integer)sizeof(sdshdr32)));
            assert(((incr >= 0 && (*(sh_l810_c19)).alloc - (*(sh_l810_c19)).length >= (uint)incr) || (incr < 0 && (*(sh_l810_c19)).length >= (uint)-incr)));
            (*(sh_l810_c19)).length += incr;
            length = (*(sh_l810_c19)).length;
        }
        break;
        case SDS_TYPE_64:
        {
            sdshdr64* sh_l817_c19 = (sdshdr64*)(s - ((integer)sizeof(sdshdr64)));
            assert(((incr >= 0 && (*(sh_l817_c19)).alloc - (*(sh_l817_c19)).length >= (uint64_t)incr) || (incr <= 0 && (*(sh_l817_c19)).length >= (uint64_t)-incr)));
            (*(sh_l817_c19)).length += incr;
            length = (*(sh_l817_c19)).length;
        }
        break;
        default:
        {
            length = 0;
        }
        break;
    }
    s[length] = '\0';
}

/**
 * Grow the sds to have the specified length. Bytes that were not part of 
 * the original length of the sds will be set to zero.
 *
 * If the specified length is smaller than the current length, no operation
 * is performed. 
 */
sds sdsgrowzero(sds s, size_t length)
{
    size_t curlen = sdslen(s);
    sds new_s = s;
    if (length > curlen)
    {
        new_s = sdsMakeRoomFor(new_s, length - curlen);
        if (new_s != nil)
        {
            memset(new_s + curlen, 0, (length - curlen + 1));
            sdssetlen(new_s, length);
        }
    }
    /* return value captured before defers */
    sds __ret_l850 = new_s;
    return __ret_l850;
}

/**
 * Append the specified binary-safe string pointed by 't' of 'length' bytes to the
 * end of the specified sds string 's'.
 *
 * After the call, the passed sds string is no longer valid and all the
 * references must be substituted with the new pointer returned by the call.
 */
sds sdscatlen(sds s, const VOID* t, size_t length)
{
    size_t curlen = sdslen(s);
    sds new_s = s;
    new_s = sdsMakeRoomFor(new_s, length);
    if (new_s != nil)
    {
        memcpy(new_s + curlen, t, length);
        sdssetlen(new_s, curlen + length);
        new_s[curlen + length] = '\0';
    }
    /* return value captured before defers */
    sds __ret_l873 = new_s;
    return __ret_l873;
}

/**
 * Append the specified null terminated C string to the sds string 's'.
 *
 * After the call, the passed sds string is no longer valid and all the
 * references must be substituted with the new pointer returned by the call.
 */
sds sdscat(sds s, const char* t)
{
    /* return value captured before defers */
    sds __ret_l885 = sdscatlen(s, t, strlen(t));
    return __ret_l885;
}

/**
 * Append the specified sds 't' to the existing sds 's'.
 *
 * After the call, the modified sds string is no longer valid and all the
 * references must be substituted with the new pointer returned by the call.
 */
sds sdscatsds(sds s, const sds t)
{
    /* return value captured before defers */
    sds __ret_l897 = sdscatlen(s, t, sdslen(t));
    return __ret_l897;
}

/**
 * Destructively modify the sds string 's' to hold the specified binary
 * safe string pointed by 't' of the length 'length' bytes.
 */
sds sdscpylen(sds s, const char* t, size_t length)
{
    sds new_s = s;
    if (sdsalloc(new_s) < length)
    {
        new_s = sdsMakeRoomFor(new_s, sdslen(new_s));
        if (new_s == nil)
        {
            /* return value captured before defers */
            sds __ret_l912 = nil;
            return __ret_l912;
        }
    }
    memcpy(new_s, t, length);
    new_s[length] = '\0';
    sdssetlen(new_s, length);
    /* return value captured before defers */
    sds __ret_l919 = new_s;
    return __ret_l919;
}

/**
 * Like sdscpylen() but 't' must be a null erminaed string so that the length
 * of the string is obtained with strlen().
 */
sds sdscpy(sds s, const char* t)
{
    /* return value captured before defers */
    sds __ret_l929 = sdscpylen(s, t, strlen(t));
    return __ret_l929;
}

/**
 * Helper for sdscatlonglong() doing the actual number -> string
 * conversion. 's' must point to a string with room for at least
 * SDS_LLSTR_SIZE bytes.
 *
 * The function returns the length of the null-terminaed string
 * representation stored at 's'. 
 */
static const integer SDS_LLSTR_SIZE = 21;
#define SDS_LLSTR_SIZE 21
static int sdsll2str(char* s, llong value)
{
    char* p = {0};
    char* q = {0};
    char aux = {0};
    ullong v = {0};
    size_t l = {0};
    if (value < 0)
    {
        if (value != LLONG_MIN)
        {
            v = -value;
        }
        else
        {
            v = (ullong)LLONG_MAX + 1;
        }
    }
    else
    {
        v = value;
    }
    p = s;
    do
    {
        {
            p++;
            (*p) = '0' + (v % 10);
            v /= 10;
        }
    }
    while (!(v == 0));
    if (value < 0)
    {
        p++;
        (*p) = '-';
    }
    l = p - s;
    (*p) = '\0';
    p--;
    q = s;
    while (q < p)
    {
        {
            aux = (*q);
            (*q) = (*p);
            (*p) = aux;
            q++;
            p--;
        }
    }
    /* return value captured before defers */
    int __ret_l991 = l;
    return __ret_l991;
}

/**
 * Identical sdsll2str(), but for unsigned long long type (ullong).
 */
static int sdsull2str(char* s, ullong value)
{
    char aux = {0};
    char* p = {0};
    char* q = {0};
    size_t l = {0};
    ullong v = value;
    p = s;
    do
    {
        {
            p++;
            (*p) = '0' + (v % 10);
            v /= 10;
        }
    }
    while (!(v == 0));
    l = p - s;
    (*p) = '\0';
    p--;
    q = s;
    while (q < p)
    {
        {
            aux = (*q);
            (*q) = (*p);
            (*p) = aux;
            q++;
            p--;
        }
    }
    /* return value captured before defers */
    int __ret_l1029 = l;
    return __ret_l1029;
}

/**
 * Create an sds string from a long long value. It is much faster than:
 *
 * sdscatprintf(sdsempty(), "%lld\n", value)
 */
sds sdsfromlonglong(llong value)
{
    char buf[21] = {0};
    int length = sdsll2str(buf, value);
    /* return value captured before defers */
    sds __ret_l1044 = sdsnewlen(buf, length);
    return __ret_l1044;
}

/**
 * Like sdscatprintf() but gets va_list instead of being variadic.
 */
sds sdscatvprintf(sds s, const char* fmt, va_list ap)
{
    va_list cpy = {0};
    char staticbuf[1024] = {0};
    char* buf = staticbuf;
    char* t = {0};
    size_t buflen = strlen(fmt) * 2;
    int bufstrlen = {0};
    if (buflen > ((integer)sizeof(staticbuf)))
    {
        buf = s_malloc(buflen);
        if (buf == nil)
        {
            /* return value captured before defers */
            sds __ret_l1065 = nil;
            return __ret_l1065;
        }
    }
    else
    {
        buflen = ((integer)sizeof(staticbuf));
    }
    while (1)
    {
        {
            va_copy(cpy, ap);
            bufstrlen = vsnprintf(buf, buflen, fmt, cpy);
            va_end(cpy);
            if (bufstrlen < 0)
            {
                if (buf != staticbuf)
                {
                    s_free(buf);
                    /* return value captured before defers */
                    sds __ret_l1080 = nil;
                    return __ret_l1080;
                }
            }
            if ((size_t)bufstrlen >= buflen)
            {
                if (buf != staticbuf)
                {
                    s_free(buf);
                }
                buflen = (size_t)bufstrlen + 1;
                buf = s_malloc(buflen);
                if (buf == nil)
                {
                    /* return value captured before defers */
                    sds __ret_l1090 = nil;
                    return __ret_l1090;
                }
                                /* INVARIANT (on loop exit) */
                continue;
            }
                        /* INVARIANT (on loop exit) */
            break;
        }
    }
    t = sdscatlen(s, buf, bufstrlen);
    if (buf != staticbuf)
    {
        s_free(buf);
    }
    /* return value captured before defers */
    sds __ret_l1102 = t;
    return __ret_l1102;
}

/**
 * Append to the sds string 's' a string obtained using printf-alike format
 * specifier.
 *
 * After the call, the modified sds string is no longer valid and all the
 * references must be substituted with the new pointer returned by the call.
 *
 * Example:
 *
 *  s := sdsnew("Sum is: ")
 *  s := sdscatprintf(s, "%d+%d = %d", a, b, a+b).
 *
 * Often you need to create a string from scratch with the printf-alike
 * format. When this is the need, just use sdsempty() as the target string:
 *
 * s := sdscatprintf(sdsempty(), "... your format ...", args)
 */
sds sdscatprintf(sds s, const char* fmt, ...)
{
    va_list ap = {0};
    char* t = {0};
    va_start(ap, fmt);
    t = sdscatvprintf(s, fmt, ap);
    va_end(ap);
    /* return value captured before defers */
    sds __ret_l1131 = t;
    return __ret_l1131;
}

/**
 * This function is similar to sdscatprintf, but much faster as it does
 * not rely on sprintf() family functions implemented by the libc that
 * are often very slow. Moreover directly handling the sds string as
 * new data is concatenated provides a performanc improvement.
 *
 * However this function only handles an incompatible subset of printf-alike
 * format specifiers:
 *
 * %s - C String
 * %S - SDS string
 * %i - signed int
 * %I - 64 bit signed integer (long long, int64_t)
 * %u - unsigned int
 * %U - 64 bit unsigned integer (unsigned long long, uint64_t)
 * %% - Verbatim "%" character.
 */
sds sdscatfmt(sds s, const char* fmt, ...)
{
    size_t initlen = sdslen(s);
    const char* f = fmt;
    long i = {0};
    va_list ap = {0};
    sds new_s = s;
    new_s = sdsMakeRoomFor(new_s, initlen + strlen(fmt) * 2);
    va_start(ap, fmt);
    f = fmt;
    i = initlen;
    while ((*f))
    {
        {
            char next = {0};
            char* str = {0};
            size_t l = {0};
            llong num = {0};
            ullong unum = {0};
            if (sdsavail(new_s) == 0)
            {
                new_s = sdsMakeRoomFor(new_s, 1);
            }
            switch ((*f))
            {
                case '%':
                {
                    next = (*(f + 1));
                    if (next == '\0')
                    {
                                                /* INVARIANT (on loop exit) */
                        break;
                    }
                    f++;
                    switch (next)
                    {
                        case 's':
                        case 'S':
                        {
                            str = va_arg(ap, pchar);
                            l = ((next == 's') ? strlen(str) : sdslen(str));
                            if (sdsavail(new_s) < l)
                            {
                                new_s = sdsMakeRoomFor(new_s, l);
                            }
                            memcpy(new_s + i, str, l);
                            sdsinclen(new_s, l);
                            i += l;
                                                        /* INVARIANT (on loop exit) */
                            break;
                        }
                        break;
                        case 'i':
                        case 'I':
                        {
                            if (next == 'i')
                            {
                                num = va_arg(ap, int);
                            }
                            else
                            {
                                num = va_arg(ap, llong);
                            }
                            {
                                char buf[21] = {0};
                                l = sdsll2str(buf, num);
                                if (sdsavail(new_s) < l)
                                {
                                    new_s = sdsMakeRoomFor(new_s, l);
                                }
                                memcpy(new_s + i, buf, l);
                                sdsinclen(new_s, l);
                                i += l;
                            }
                                                        /* INVARIANT (on loop exit) */
                            break;
                        }
                        break;
                        case 'u':
                        case 'U':
                        {
                            if (next == 'u')
                            {
                                unum = va_arg(ap, uint);
                            }
                            else
                            {
                                unum = va_arg(ap, ullong);
                            }
                            {
                                char buf[21] = {0};
                                l = sdsull2str(buf, unum);
                                if (sdsavail(new_s) < l)
                                {
                                    new_s = sdsMakeRoomFor(new_s, l);
                                }
                                memcpy(new_s + i, buf, l);
                                sdsinclen(new_s, l);
                                i += l;
                            }
                                                        /* INVARIANT (on loop exit) */
                            break;
                        }
                        break;
                        default:
                        {
                            new_s[i] = next;
                            i++;
                            sdsinclen(new_s, 1);
                                                        /* INVARIANT (on loop exit) */
                            break;
                        }
                        break;
                    }
                                        /* INVARIANT (on loop exit) */
                    break;
                }
                break;
                default:
                {
                    new_s[i] = (*f);
                    i++;
                    sdsinclen(new_s, 1);
                                        /* INVARIANT (on loop exit) */
                    break;
                }
                break;
            }
            f++;
        }
    }
    va_end(ap);
    new_s[i] = '\0';
    /* return value captured before defers */
    sds __ret_l1255 = new_s;
    return __ret_l1255;
}

/**
 * Remove the part of the string from left and from right composed just of
 * contiguous characters found in 'cset', that are a null terminated C string.
 *
 * After the call, the modified sds string is no longer valid and all the 
 * references must be substituted with the new pointer returned by the call.
 *
 * Example:
 *
 *  s := sdsnew("AA...AA.a.aa.aHelloWorld     :::")
 *  s := sdstrim(s, "Aa. :")
 *  printf("%s\n", s)
 *
 * Output will be just "HelloWorld".
 */
sds sdstrim(sds s, const char* cset)
{
    char* end_ = {0};
    char* sp = {0};
    char* ep = {0};
    size_t length = {0};
    sp = s;
    end_ = s + sdslen(s) - 1;
    ep = end_;
    while (sp <= end_ && strchr(cset, (*sp)))
    {
        {
            sp++;
        }
    }
    while (ep > sp && strchr(cset, (*ep)))
    {
        {
            ep--;
        }
    }
    length = (ep - sp) + 1;
    if (s != sp)
    {
        memmove(s, sp, length);
    }
    s[length] = '\0';
    sdssetlen(s, length);
    /* return value captured before defers */
    sds __ret_l1294 = s;
    return __ret_l1294;
}

/**
 * Turn the string into a smaller (or equal) string containing only the
 * substring specified by the 'start' and 'end' endexes.
 *
 * start and end can be negative, where -1 means the last character of the
 * string, -2 the penultimate character, and so forth.
 *
 * The interval is inclusive, so the start and end characters will be part
 * of the resulting string.
 *
 * The string is modified in-place
 *
 * Example:
 *
 * s := sdsnew("Hello World")
 * sdsrange(s, 1, -1)  =>  "ello World"
 */
void sdsrange(sds s, ssize_t start, ssize_t end_)
{
}


void Tsds(void)
{
}
