/* =====================================
 * Generated by Mod-c 0.26.5
 * PROGRAM nhello
 * ===================================== */

#include "nhello.h"

/**
 * ncurses hello world.
 *
 * To run:
 * `tmodc nhello.mc -C`
 * `cc nhello.c -lncurses -o nhello`
 */
#include "ncurses.h"

void nhello(void)
{
    initscr();
    printw("Hello World !!!");
    refresh();
    getch();
    endwin();
}

int main(void)
{
    nhello();
    return 0;
}
