/* =====================================
 * Generated by Mod-c 0.26.5
 * HEADER nhello PROGRAM
 * ===================================== */

#ifndef MODC_PROGRAM_nhello_H
#define MODC_PROGRAM_nhello_H

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

#define nil ((void *)0)
#define NIL nil
typedef uint8_t byte;
typedef const char* string;
typedef int integer;
typedef unsigned int cardinal;
typedef float real;

/**
 * ncurses hello world.
 *
 * To run:
 * `tmodc nhello.mc -C`
 * `cc nhello.c -lncurses -o nhello`
 */

/* === IMPORT === */
#include "ncurses.h"

void nhello(void);

#endif /* MODC_PROGRAM_nhello_H */
