/* =====================================
 * Generated by Mod-c 0.26.3
 * HEADER fnbox MODULE
 * ===================================== */

#ifndef MODC_MODULE_fnbox_H
#define MODC_MODULE_fnbox_H

/* === TYPE EXPORT === */
typedef integer (*TFn)(integer n);

/* === TYPE EXPORT === */
typedef struct TBox TBox;
typedef struct TBox {
    TFn fn;
} TBox;

/* === MODULE === */
void fnbox(void);

#endif /* MODC_MODULE_fnbox_H */
