/* =====================================
 * Generated by Mod-c 0.26.5
 * HEADER wpoint MODULE
 * ===================================== */

#ifndef MODC_MODULE_wpoint_H
#define MODC_MODULE_wpoint_H

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

#define nil ((void *)0)
#define NIL nil
typedef uint8_t byte;
typedef const char* string;
typedef int integer;
typedef unsigned int cardinal;
typedef float real;

/* === TYPE EXPORT === */
typedef struct TWPoint TWPoint;
typedef struct TWPoint {
    int32_t x;
    int32_t y;
} TWPoint;

void wpoint(void);

#endif /* MODC_MODULE_wpoint_H */
