/* =====================================
 * Generated by Mod-c 0.26.9
 * HEADER codegen_c MODULE
 * ===================================== */

#ifndef MODC_MODULE_codegen_c_H
#define MODC_MODULE_codegen_c_H

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

#define nil ((void *)0)
#define NIL nil
typedef uint8_t byte;
typedef int integer;
typedef unsigned int cardinal;
typedef float real;

/**
 * TMod-c
 * By M. Scott Reynolds
 * Date 18 April 2026
 *
 * codegen_c.c -    Basic C code generator from Mod-c AST
 *              Phase 1: simple translation of program, declarations,
 *              statements, expressions, and array indexing.
 *              Updated 23 April 2026: WHILE, FOR, REPEAT, LOOP
 *              full IF/ELSIF/ELSE, array literals beyond {0}, and
 *              compound assignments, ASSERT, SIZEOF, and
 *              remaining small self-hosting fixes.
 * 07 May 2026  Add NODE_BREAK, NODE_CONTINUE
 * 14 May 2026  Refactored to use CodegenContext (DynBuf*, indent, parent, etc.)
 *              for cleaner recursion and future scope/defer support.
 * 30 May 2026  RENAMED from codegen.c to codegen_c.c
 * 10 June 2026 Add codegen for SWITCH (explicit breaks for no-fallthrough,
 *              ELSE required -> default:, comma labels as cascaded cases).
 * Port to TMod-c started 6 Oct 2026.
 */

/* === IMPORT === */
#include "codegen_common.h"

/* === IMPORT === */
#include "codegen_dbc.h"

/* === IMPORT === */
#include "dynbuf.h"

/* === IMPORT === */
#include "Lexer.h"

/* === IMPORT === */
#include "node.h"

/* === IMPORT === */
#include "stddef.h"

/* === IMPORT === */
#include "stdio.h"

/* === IMPORT === */
#include "stdlib.h"

/* === IMPORT === */
#include "ttype.h"

/* === IMPORT === */
#include "version.h"

/**
 * Generate C source code from the given AST in the CodegenContext.
 * The output is written into the provided DynBuf (which must be initialized),
 * also set in the CodegenContext.
 * Exits program on fatal error.
 */

/**
 * Emit PROCEDURE or FUNCTION declaration.
 * Maps to C function with proper return type and parameters.
 * Body is emitted as a block.
 * If no body is defined, treat it as a prototype.
 */

/**
 * Emit DEFER (phase 1: simple comment wrapper).
 */

/**
 * Emit DEBUG statements if debug flag has been set in the context.
 */

/**
 * Emit ASSERT (cond [, hint])
 */

/**
 * Emit IF / ELSIF / ELSE chain.
 * Handles the full TMod-c if-then-elsif-else-end structure.
 */

/**
 * Emit WHILE ... DO ... END
 */

/**
 * Emit FOR ... TO/DOWNTO ... BY ... DO ... END
 */

/**
 * Emit REPEAT ... UNTIL ...
 */

/**
 * Emit LOOP ... END (infinite loop)
 */

/**
 * Emit SWITCH ... OF ... CASE ... ELSE ... END
 * Maps to a C switch. No fallthrough (we emit explic break; after each arm's body).
 * Comma lables become successive "case X:" (they share the following body until the break)
 * ELSE (required in source) becomes "default:". A break; is emitted after the default arm
 * for symetry.
 */

/**
 * Emit a TYPE declaration.
 * Simple types for now.
 */

/**
 * Index of stmt in block->block.stmts, or (size_t) - 1 if not direct child.
 * DEFER nodes are stored both in stmts[] and in defers[]; pointer equality
 * is the link.
 */

/**
 * Emit a DEFER statement.
 * C2y / Language Report 7.3: a defer runs only if contorl passed the
 * DEFER stateent. ctx.stmt_index is the cutoff in this block (see
 * CodegenContext.stmt_index); LIFO amongh those that qualify.
 */

/**
 * Emit defers by walking up the context chain until we reach the
 * enclosing function. Used by RETURN statements.
 */

/**
 * Emit defers by walking up the context chain until we reach the
 * enclosing loop. Used by BREAK and CONTINUE statements.
 */

/**
 * Emit RETURN statement with proper DEFER cleanup.
 * Grammar: "RETURN" [ expression ]
 */

/**
 * Emit BREAK statement with proper DEFER cleaup
 * Grammar "BREAK"
 */

/**
 * Emit CONTINUE statement wiht proper DEFER cleanup.
 * Grammar: "CONTINUE"
 */

/**
 * Emit a single statement
 */

/**
 * Emit BEGIN ... END block (statement sequence)
 */

/**
 * Generate a separate main(...) wraper for NODE_PROGRAM
 */

/**
 * Generate module entry point using module name, parameters, and block.
 */

/**
 * Emit top-level program / module
 */

/**
 * Public entry point: generate C code from AST
 * Writes to the provided DynBuf.
 * Exits on fatal error.
 */

void codegen_c(CodegenContext ctx);

#endif /* MODC_MODULE_codegen_c_H */
