/* =====================================
 * Generated by Mod-c 0.26.9
 * MODULE codegen_c
 * ===================================== */

#include "codegen_c.h"

void codegen_c(CodegenContext ctx);

/**
 * TMod-c
 * By M. Scott Reynolds
 * Date 18 April 2026
 *
 * codegen_c.c -    Basic C code generator from Mod-c AST
 *              Phase 1: simple translation of program, declarations,
 *              statements, expressions, and array indexing.
 *              Updated 23 April 2026: WHILE, FOR, REPEAT, LOOP
 *              full IF/ELSIF/ELSE, array literals beyond {0}, and
 *              compound assignments, ASSERT, SIZEOF, and
 *              remaining small self-hosting fixes.
 * 07 May 2026  Add NODE_BREAK, NODE_CONTINUE
 * 14 May 2026  Refactored to use CodegenContext (DynBuf*, indent, parent, etc.)
 *              for cleaner recursion and future scope/defer support.
 * 30 May 2026  RENAMED from codegen.c to codegen_c.c
 * 10 June 2026 Add codegen for SWITCH (explicit breaks for no-fallthrough,
 *              ELSE required -> default:, comma labels as cascaded cases).
 * Port to TMod-c started 6 Oct 2026.
 */
#include "codegen_common.h"
#include "codegen_dbc.h"
#include "dynbuf.h"
#include "Lexer.h"
#include "node.h"
#include "stddef.h"
#include "stdio.h"
#include "stdlib.h"
#include "ttype.h"
#include "version.h"
/**
 * Generate C source code from the given AST in the CodegenContext.
 * The output is written into the provided DynBuf (which must be initialized),
 * also set in the CodegenContext.
 * Exits program on fatal error.
 */
static void codegen_c_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_block(const Node* n, CodegenContext ctx);
static void codegen_c_if_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_while_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_for_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_repeat_until_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_loop_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_switch_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_defer_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_assert_stmt(const Node* n, CodegenContext ctx);
static void codegen_c_proc_or_func(const Node* n, CodegenContext ctx);
static void codegen_c_program(const Node* n, CodegenContext ctx);
static void codegen_c_type_decl(const Node* n, CodegenContext ctx);
/**
 * Emit PROCEDURE or FUNCTION declaration.
 * Maps to C function with proper return type and parameters.
 * Body is emitted as a block.
 * If no body is defined, treat it as a prototype.
 */
static void codegen_c_proc_or_func(const Node* n, CodegenContext ctx)
{
    if (n == nil)
    {
                return;
    }
    codegen_common_proc_or_func(n, ctx);
    if (((*(n)).proc_decl).body != nil)
    {
        CodegenContext child = {0};
        dynbuf_append_char((ctx).out, '\n');
        child = ctx_push(&ctx, n);
        codegen_c_block(((*(n)).proc_decl).body, child);
    }
    else
    {
        dynbuf_append_char((ctx).out, ';');
    }
    dynbuf_append((ctx).out, "\n");
}

/**
 * Emit DEFER (phase 1: simple comment wrapper).
 */
static void codegen_c_defer_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil)
    {
                return;
    }
    dynbuf_append((ctx).out, "/* DEFER begin */\n");
}

/**
 * Emit DEBUG statements if debug flag has been set in the context.
 */
static void codegen_c_debug_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil)
    {
                return;
    }
    if ((ctx).debug_enabled)
    {
        dynbuf_append((ctx).out, "/* DEBUG */\n");
        codegen_c_stmt(((*(n)).debug_stmt).action, ctx);
    }
}

/**
 * Emit ASSERT (cond [, hint])
 */
static void codegen_c_assert_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_ASSERT || (ctx).assert_off)
    {
                return;
    }
    dynbuf_append((ctx).out, "assert(");
    codegen_common_expr(((*(n)).assert_stmt).condition, ctx);
    dynbuf_append((ctx).out, ");");
    if (((*(n)).assert_stmt).const_expr != nil)
    {
        dynbuf_append((ctx).out, " /* ");
        codegen_common_expr(((*(n)).assert_stmt).const_expr, ctx);
        dynbuf_append((ctx).out, " */");
    }
    dynbuf_append((ctx).out, "\n");
}

/**
 * Emit IF / ELSIF / ELSE chain.
 * Handles the full TMod-c if-then-elsif-else-end structure.
 */
static void codegen_c_if_stmt(const Node* n, CodegenContext ctx)
{
    const Node* else_ = {0};
    const Node* elsif_ = {0};
    if (n == nil || (*(n)).kind != NODE_IF)
    {
        dynbuf_append((ctx).out, "/* TODO: codegen_c_if_stmt: invalid if node */\n");
                return;
    }
    dynbuf_append((ctx).out, "if (");
    codegen_common_expr(((*(n)).if_stmt).cond, ctx);
    dynbuf_append((ctx).out, ")\n");
    {
        CodegenContext child = ctx_push(&ctx, n);
        codegen_c_stmt(((*(n)).if_stmt).then_, child);
    }
    else_ = ((*(n)).if_stmt).else_;
    elsif_ = ((*(n)).if_stmt).elsif_;
    while (elsif_ != nil)
    {
        {
            CodegenContext child = {0};
            emit_indent((ctx).out, (ctx).indent);
            dynbuf_append((ctx).out, "else if (");
            codegen_common_expr(((*(elsif_)).if_stmt).cond, ctx);
            dynbuf_append((ctx).out, ")\n");
            child = ctx_push(&ctx, elsif_);
            codegen_c_stmt(((*(elsif_)).if_stmt).then_, child);
            else_ = ((*(elsif_)).if_stmt).else_;
            elsif_ = ((*(elsif_)).if_stmt).elsif_;
        }
    }
    if (else_ != nil)
    {
        CodegenContext child = {0};
        emit_indent((ctx).out, (ctx).indent);
        dynbuf_append((ctx).out, "else\n");
        child = ctx_push(&ctx, n);
        codegen_c_stmt(else_, child);
    }
}

/**
 * Emit WHILE ... DO ... END
 */
static void codegen_c_while_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_WHILE)
    {
                return;
    }
    dynbuf_append((ctx).out, "while (");
    codegen_common_expr(((*(n)).while_stmt).cond, ctx);
    dynbuf_append((ctx).out, ")\n");
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "{\n");
    (ctx).indent++;
    {
        CodegenContext child = ctx_push(&ctx, n);
        (child).enclosing_loop = n;
        codegen_dbc_emit_invariants(n, child);
        codegen_c_stmt(((*(n)).while_stmt).body, child);
        (ctx).indent--;
        emit_indent((ctx).out, (ctx).indent);
        dynbuf_append((ctx).out, "}\n");
        codegen_dbc_emit_invariants(n, ctx);
    }
}

/**
 * Emit FOR ... TO/DOWNTO ... BY ... DO ... END
 */
static void codegen_c_for_stmt(const Node* n, CodegenContext ctx)
{
    char buf[32] = {0};
    if (n == nil || (*(n)).kind != NODE_FOR)
    {
                return;
    }
    dynbuf_append((ctx).out, "{\n");
    (ctx).indent++;
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "const long long __for_end_l");
    snprintf(buf, ((integer)sizeof(buf)), "%d", ((*(n)).token).line);
    dynbuf_append((ctx).out, buf);
    dynbuf_append((ctx).out, " = (long long)(");
    codegen_common_expr(((*(n)).for_stmt).end_, ctx);
    dynbuf_append((ctx).out, ");\n");
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "for (");
    dynbuf_appendn((ctx).out, ((*(n)).for_stmt).var_name, ((*(n)).for_stmt).var_len);
    dynbuf_append((ctx).out, " = ");
    codegen_common_expr(((*(n)).for_stmt).start_, ctx);
    dynbuf_append((ctx).out, "; ");
    dynbuf_append((ctx).out, "(long long)(");
    dynbuf_appendn((ctx).out, ((*(n)).for_stmt).var_name, ((*(n)).for_stmt).var_len);
    dynbuf_append((ctx).out, ")");
    if (((*(n)).for_stmt).step >= 0)
    {
        dynbuf_append((ctx).out, " <= __for_end_l");
    }
    else
    {
        dynbuf_append((ctx).out, " >= __for_end_l");
    }
    snprintf(buf, ((integer)sizeof(buf)), "%d", ((*(n)).token).line);
    dynbuf_append((ctx).out, buf);
    dynbuf_append((ctx).out, "; ");
    dynbuf_appendn((ctx).out, ((*(n)).for_stmt).var_name, ((*(n)).for_stmt).var_len);
    if (((*(n)).for_stmt).step == 1)
    {
        dynbuf_append((ctx).out, "++");
    }
    else if (((*(n)).for_stmt).step == -1)
    {
        dynbuf_append((ctx).out, "--");
    }
    else if (((*(n)).for_stmt).step > 0)
    {
        dynbuf_append((ctx).out, " += ");
        snprintf(buf, ((integer)sizeof(buf)), "%d", ((*(n)).for_stmt).step);
        dynbuf_append((ctx).out, buf);
    }
    else
    {
        dynbuf_append((ctx).out, " -= ");
        snprintf(buf, ((integer)sizeof(buf)), "%d", -((*(n)).for_stmt).step);
        dynbuf_append((ctx).out, buf);
    }
    dynbuf_append((ctx).out, ")\n");
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "{\n");
    (ctx).indent++;
    {
        CodegenContext child = ctx_push(&ctx, n);
        (child).enclosing_loop = n;
        codegen_dbc_emit_invariants(n, child);
        codegen_c_stmt(((*(n)).for_stmt).body, child);
        (ctx).indent--;
    }
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "}\n");
    codegen_dbc_emit_invariants(n, ctx);
    (ctx).indent--;
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "}\n");
}

/**
 * Emit REPEAT ... UNTIL ...
 */
static void codegen_c_repeat_until_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_REPEAT_UNTIL)
    {
                return;
    }
    dynbuf_append((ctx).out, "do\n");
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "{\n");
    (ctx).indent++;
    {
        CodegenContext child = ctx_push(&ctx, n);
        codegen_dbc_emit_invariants(n, child);
        codegen_c_stmt(((*(n)).repeat_until).body, child);
        (ctx).indent--;
    }
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "}\n");
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "while (!(");
    codegen_common_expr(((*(n)).repeat_until).cond, ctx);
    dynbuf_append((ctx).out, "));\n");
    codegen_dbc_emit_invariants(n, ctx);
}

/**
 * Emit LOOP ... END (infinite loop)
 */
static void codegen_c_loop_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_LOOP)
    {
                return;
    }
    dynbuf_append((ctx).out, "while (1)\n");
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "{\n");
    (ctx).indent++;
    {
        CodegenContext child = ctx_push(&ctx, n);
        (child).enclosing_loop = n;
        codegen_dbc_emit_invariants(n, child);
        codegen_c_stmt(((*(n)).loop_stmt).body, child);
        (ctx).indent--;
    }
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "}\n");
    codegen_dbc_emit_invariants(n, ctx);
}

/**
 * Emit SWITCH ... OF ... CASE ... ELSE ... END
 * Maps to a C switch. No fallthrough (we emit explic break; after each arm's body).
 * Comma lables become successive "case X:" (they share the following body until the break)
 * ELSE (required in source) becomes "default:". A break; is emitted after the default arm
 * for symetry.
 */
static void codegen_c_switch_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_SWITCH)
    {
        dynbuf_append((ctx).out, "/* TODO: codegen_c_switch_stmt: invalid switch node */\n");
                return;
    }
    dynbuf_append((ctx).out, "switch (");
    codegen_common_expr(((*(n)).switch_stmt).expr, ctx);
    dynbuf_append((ctx).out, ")\n");
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "{\n");
    {
        CodegenContext arm_ctx = ctx_push(&ctx, n);
        size_t i = {0};
        (arm_ctx).indent = (ctx).indent + 1;
        {
            const long long __for_end_l440 = (long long)(((*(n)).switch_stmt).case_count - 1);
            for (i = 0; (long long)(i) <= __for_end_l440; i++)
            {
                {
                    SwitchCase* c = ((*(n)).switch_stmt).cases[i];
                    size_t j = {0};
                    if (c == nil)
                    {
                                                /* INVARIANT (on loop exit) */
                        continue;
                    }
                    {
                        const long long __for_end_l448 = (long long)((*(c)).label_count - 1);
                        for (j = 0; (long long)(j) <= __for_end_l448; j++)
                        {
                            {
                                emit_indent((ctx).out, (arm_ctx).indent);
                                dynbuf_append((ctx).out, "case ");
                                codegen_common_expr((*(c)).labels[j], arm_ctx);
                                dynbuf_append((ctx).out, ":\n");
                            }
                        }
                    }
                    codegen_c_stmt((*(c)).body, arm_ctx);
                    emit_indent((ctx).out, (arm_ctx).indent);
                    dynbuf_append((ctx).out, "break;\n");
                }
            }
        }
        emit_indent((ctx).out, (arm_ctx).indent);
        dynbuf_append((ctx).out, "default:\n");
        codegen_c_stmt(((*(n)).switch_stmt).else_body, arm_ctx);
        emit_indent((ctx).out, (arm_ctx).indent);
        dynbuf_append((ctx).out, "break;\n");
    }
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "}\n");
}

/**
 * Emit a TYPE declaration.
 * Simple types for now.
 */
static void codegen_c_type_decl(const Node* n, CodegenContext ctx)
{
    if (n == nil)
    {
                return;
    }
    if (!((*(n)).type_decl).is_exported)
    {
        codegen_common_type_decl(n, ctx);
    }
}

/**
 * Index of stmt in block->block.stmts, or (size_t) - 1 if not direct child.
 * DEFER nodes are stored both in stmts[] and in defers[]; pointer equality
 * is the link.
 */
static size_t codegen_c_block_stmt_index(const Node* block, const Node* stmt)
{
    size_t i = {0};
    if (block == nil || (*(block)).kind != NODE_BLOCK || stmt == nil)
    {
        /* return value captured before defers */
        size_t __ret_l510 = (size_t)(-1);
        return __ret_l510;
    }
    {
        const long long __for_end_l513 = (long long)(((*(block)).block).count - 1);
        for (i = 0; (long long)(i) <= __for_end_l513; i++)
        {
            {
                if (((*(block)).block).stmts[i] == stmt)
                {
                    /* return value captured before defers */
                    size_t __ret_l515 = i;
                    return __ret_l515;
                }
            }
        }
    }
    /* return value captured before defers */
    size_t __ret_l518 = (size_t)(-1);
    return __ret_l518;
}

static bool codegen_c_block_has_reached_defer(const Node* block, size_t cutoff)
{
    size_t i = {0};
    size_t at = {0};
    if (block == nil || (*(block)).kind != NODE_BLOCK)
    {
        /* return value captured before defers */
        bool __ret_l529 = false;
        return __ret_l529;
    }
    {
        const long long __for_end_l532 = (long long)(((*(block)).block).defer_count - 1);
        for (i = 0; (long long)(i) <= __for_end_l532; i++)
        {
            {
                const Node* d = ((*(block)).block).defers[i];
                if (d == nil)
                {
                                        /* INVARIANT (on loop exit) */
                    continue;
                }
                at = codegen_c_block_stmt_index(block, d);
                if (at != (size_t)(-1) && at < cutoff)
                {
                    /* return value captured before defers */
                    bool __ret_l539 = true;
                    return __ret_l539;
                }
            }
        }
    }
    /* return value captured before defers */
    bool __ret_l542 = false;
    return __ret_l542;
}

/**
 * Emit a DEFER statement.
 * C2y / Language Report 7.3: a defer runs only if contorl passed the
 * DEFER stateent. ctx.stmt_index is the cutoff in this block (see
 * CodegenContext.stmt_index); LIFO amongh those that qualify.
 */
static void codegen_c_emit_defers(const Node* block_node, CodegenContext ctx)
{
    size_t cutoff = {0};
    size_t i = {0};
    if (block_node == nil || (*(block_node)).kind != NODE_BLOCK)
    {
                return;
    }
    cutoff = (ctx).stmt_index;
    {
        const long long __for_end_l565 = (long long)(1);
        for (i = ((*(block_node)).block).defer_count; (long long)(i) >= __for_end_l565; i--)
        {
            {
                const Node* d = ((*(block_node)).block).defers[i - 1];
                size_t at = {0};
                if (d == nil)
                {
                                        /* INVARIANT (on loop exit) */
                    continue;
                }
                at = codegen_c_block_stmt_index(block_node, d);
                if (at == (size_t)(-1) || at >= cutoff)
                {
                                        /* INVARIANT (on loop exit) */
                    continue;
                }
                emit_indent((ctx).out, (ctx).indent);
                dynbuf_append((ctx).out, "/* DEFER end */\n");
                codegen_c_stmt(((*(d)).defer_stmt).action, ctx);
            }
        }
    }
}

/**
 * Emit defers by walking up the context chain until we reach the
 * enclosing function. Used by RETURN statements.
 */
static void codegen_c_emit_defers_to_func(CodegenContext ctx)
{
    CodegenContext current = ctx;
    const Node* target_func = (ctx).enclosing_func;
    while ((current).parent_ctx != nil)
    {
        {
            if ((current).parent_node != nil && (*((current).parent_node)).kind == NODE_BLOCK)
            {
                if (codegen_c_block_has_reached_defer((current).parent_node, (current).stmt_index))
                {
                    emit_indent((ctx).out, (ctx).indent);
                    dynbuf_append((ctx).out, "/* DEFER cleanup (unwinding to function) */\n");
                    codegen_c_emit_defers((current).parent_node, current);
                }
            }
            if ((current).enclosing_func != nil && (current).parent_node == target_func)
            {
                                /* INVARIANT (on loop exit) */
                break;
            }
            current = (*(current).parent_ctx);
        }
    }
}

/**
 * Emit defers by walking up the context chain until we reach the
 * enclosing loop. Used by BREAK and CONTINUE statements.
 */
static void codegen_c_emit_defers_to_loop(CodegenContext ctx)
{
    CodegenContext current = ctx;
    const Node* target_loop = (ctx).enclosing_loop;
    while ((current).parent_ctx != nil)
    {
        {
            if ((current).parent_node != nil && (*((current).parent_node)).kind == NODE_BLOCK)
            {
                if (codegen_c_block_has_reached_defer((current).parent_node, (current).stmt_index))
                {
                    dynbuf_append((ctx).out, "/* DEFER cleanup (unwinding to loop) */\n");
                    codegen_c_emit_defers((current).parent_node, current);
                }
            }
            if ((current).parent_node != nil && (current).parent_node == target_loop)
            {
                                /* INVARIANT (on loop exit) */
                break;
            }
            current = (*(current).parent_ctx);
        }
    }
}

/**
 * Emit RETURN statement with proper DEFER cleanup.
 * Grammar: "RETURN" [ expression ]
 */
static void codegen_c_return_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_RETURN)
    {
                return;
    }
    codegen_dbc_emit_ensures_to_func(ctx);
    if (((*(n)).ret).expr != nil)
    {
        int line = ((*(n)).token).line;
        TType* ret_type = nil;
        char buf[32] = {0};
        dynbuf_append((ctx).out, "/* return value captured before defers */\n");
        emit_indent((ctx).out, (ctx).indent);
        if ((ctx).enclosing_func != nil)
        {
            ret_type = ((*((ctx).enclosing_func)).func_decl).return_type;
        }
        else if ((ctx).ast != nil && (*((ctx).ast)).kind == NODE_PROGRAM)
        {
            ret_type = ((*((ctx).ast)).program_decl).return_type;
        }
        emit_return_type((ctx).out, ret_type);
        dynbuf_append_char((ctx).out, ' ');
        dynbuf_append((ctx).out, "__ret_l");
        snprintf(buf, ((integer)sizeof(buf)), "%d", line);
        dynbuf_append((ctx).out, buf);
        dynbuf_append((ctx).out, " = ");
        codegen_common_expr(((*(n)).ret).expr, ctx);
        dynbuf_append((ctx).out, ";\n");
        codegen_c_emit_defers_to_func(ctx);
        emit_indent((ctx).out, (ctx).indent);
        dynbuf_append((ctx).out, "return __ret_l");
        dynbuf_append((ctx).out, buf);
        dynbuf_append((ctx).out, ";\n");
    }
    else
    {
        codegen_c_emit_defers_to_func(ctx);
        emit_indent((ctx).out, (ctx).indent);
        dynbuf_append((ctx).out, "return;\n");
    }
}

/**
 * Emit BREAK statement with proper DEFER cleaup
 * Grammar "BREAK"
 */
static void codegen_c_break_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_BREAK)
    {
                return;
    }
    codegen_c_emit_defers_to_loop(ctx);
    codegen_dbc_emit_invariants_to_loop(ctx);
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "break;\n");
}

/**
 * Emit CONTINUE statement wiht proper DEFER cleanup.
 * Grammar: "CONTINUE"
 */
static void codegen_c_continue_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_CONTINUE)
    {
                return;
    }
    codegen_c_emit_defers_to_loop(ctx);
    codegen_dbc_emit_invariants_to_loop(ctx);
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "continue;\n");
}

/**
 * Emit a single statement
 */
static void codegen_c_stmt(const Node* n, CodegenContext ctx)
{
    if (n == nil)
    {
                return;
    }
    emit_indent((ctx).out, (ctx).indent);
    switch ((*(n)).kind)
    {
        case NODE_DOC_COMMENT:
        {
            emit_doc_comment_as_c((ctx).out, n);
        }
        break;
        case NODE_PREPROCESSOR:
        {
            codegen_common_preprocessor(n, ctx);
        }
        break;
        case NODE_DEFINE:
        {
            codegen_common_define(n, ctx);
        }
        break;
        case NODE_EXPR_STMT:
        {
            codegen_common_expr(((*(n)).expr_stmt).expr, ctx);
            dynbuf_append((ctx).out, ";\n");
        }
        break;
        case NODE_ASSIGN:
        {
            codegen_common_expr(n, ctx);
            dynbuf_append((ctx).out, ";\n");
        }
        break;
        case NODE_RETURN:
        {
            codegen_c_return_stmt(n, ctx);
        }
        break;
        case NODE_BREAK:
        {
            codegen_c_break_stmt(n, ctx);
        }
        break;
        case NODE_CONTINUE:
        {
            codegen_c_continue_stmt(n, ctx);
        }
        break;
        case NODE_DEFER:
        {
            codegen_c_defer_stmt(n, ctx);
        }
        break;
        case NODE_DEBUG:
        {
            codegen_c_debug_stmt(n, ctx);
        }
        break;
        case NODE_IF:
        {
            codegen_c_if_stmt(n, ctx);
        }
        break;
        case NODE_WHILE:
        {
            codegen_c_while_stmt(n, ctx);
        }
        break;
        case NODE_FOR:
        {
            codegen_c_for_stmt(n, ctx);
        }
        break;
        case NODE_REPEAT_UNTIL:
        {
            codegen_c_repeat_until_stmt(n, ctx);
        }
        break;
        case NODE_LOOP:
        {
            codegen_c_loop_stmt(n, ctx);
        }
        break;
        case NODE_SWITCH:
        {
            codegen_c_switch_stmt(n, ctx);
        }
        break;
        case NODE_ASSERT:
        {
            codegen_c_assert_stmt(n, ctx);
        }
        break;
        case NODE_LET_DECL:
        case NODE_VAR_DECL:
        case NODE_CONST_DECL:
        {
            size_t i = {0};
            {
                const long long __for_end_l809 = (long long)(((*(n)).var_decl).count - 1);
                for (i = 0; (long long)(i) <= __for_end_l809; i++)
                {
                    {
                        const Node* item = ((*(n)).var_decl).items[i];
                        if (item == nil)
                        {
                                                        /* INVARIANT (on loop exit) */
                            continue;
                        }
                        if (i > 0)
                        {
                            emit_indent((ctx).out, (ctx).indent);
                        }
                        if (((*(n)).var_decl).is_extern)
                        {
                            dynbuf_append((ctx).out, "extern ");
                        }
                        else if (((*(n)).var_decl).is_static || (ctx).parent_node == nil)
                        {
                            dynbuf_append((ctx).out, "static ");
                        }
                        if ((*(n)).kind == NODE_CONST_DECL)
                        {
                            dynbuf_append((ctx).out, "const ");
                        }
                        if ((*(n)).kind == NODE_LET_DECL)
                        {
                            if (((*(item)).var_item).item_type != nil)
                            {
                                emit_type_specifier((ctx).out, ((*(item)).var_item).item_type, nil, 0, false, false, false, false);
                                dynbuf_append_char((ctx).out, ' ');
                            }
                            else
                            {
                                dynbuf_append((ctx).out, "int ");
                            }
                            emit_let_binding_name((ctx).out, ((*(item)).var_item).name, ((*(item)).var_item).name_len, item);
                        }
                        else
                        {
                            emit_var_decl((ctx).out, ((*(item)).var_item).name, ((*(item)).var_item).name_len, ((*(item)).var_item).item_type);
                        }
                        if (!((*(n)).var_decl).is_extern)
                        {
                            if (((*(item)).var_item).initializer != nil)
                            {
                                dynbuf_append((ctx).out, " = ");
                                codegen_common_expr(((*(item)).var_item).initializer, ctx);
                            }
                            else
                            {
                                dynbuf_append((ctx).out, " = {0}");
                            }
                        }
                        dynbuf_append((ctx).out, ";\n");
                    }
                }
            }
        }
        break;
        case NODE_PROC_DECL:
        case NODE_FUNC_DECL:
        {
            codegen_c_proc_or_func(n, ctx);
        }
        break;
        case NODE_BLOCK:
        {
            codegen_c_block(n, ctx);
        }
        break;
        case NODE_TYPE_DECL:
        {
            codegen_c_type_decl(n, ctx);
        }
        break;
        case NODE_INC:
        case NODE_DEC:
        {
            codegen_common_inc_dec(n, ctx, true);
        }
        break;
        case NODE_STRUCT_DECL:
        case NODE_PROGRAM:
        case NODE_VAR_ITEM:
        case NODE_CONST_ITEM:
        case NODE_LET_ITEM:
        case NODE_PARAM:
        case NODE_PARAM_LIST:
        case NODE_IMPORT:
        case NODE_IMPORT_ITEM:
        case NODE_FIELD_DECL:
        case NODE_METHOD_TYPE:
        case NODE_ARRAY_TYPE:
        case NODE_ARRAY_LITERAL:
        case NODE_ARRAY_INDEX:
        case NODE_FIELD_ACCESS:
        case NODE_ELSIF:
        case NODE_ELSE:
        case NODE_SIZEOF:
        case NODE_COUNTOF:
        case NODE_BINARY:
        case NODE_UNARY:
        case NODE_TERNARY:
        case NODE_CAST:
        case NODE_LITERAL:
        case NODE_IDENT:
        case NODE_CALL:
        case NODE_PAREN:
        {
            dynbuf_append((ctx).out, "/* TODO: codegen_c_stmt: stmt kind ");
            dynbuf_append((ctx).out, TokenKind__string((TokenKind)((*(n)).token).kind));
            dynbuf_append((ctx).out, " */\n");
        }
        break;
        default:
        {
            dynbuf_append((ctx).out, "/* TODO: codegen_c_stmt: stmt kind ");
            dynbuf_append((ctx).out, TokenKind__string((TokenKind)((*(n)).token).kind));
            dynbuf_append((ctx).out, " */\n");
        }
        break;
    }
}

/**
 * Emit BEGIN ... END block (statement sequence)
 */
static void codegen_c_block(const Node* n, CodegenContext ctx)
{
    if (n == nil)
    {
                return;
    }
    dynbuf_append((ctx).out, "{\n");
    {
        CodegenContext child_ctx = ctx_push(&ctx, n);
        size_t i = {0};
        bool early_exit_in_block = false;
        (child_ctx).indent = (ctx).indent + 1;
        codegen_dbc_emit_requires(n, child_ctx);
        {
            const long long __for_end_l916 = (long long)(((*(n)).block).count - 1);
            for (i = 0; (long long)(i) <= __for_end_l916; i++)
            {
                {
                    (child_ctx).stmt_index = i;
                    codegen_c_stmt(((*(n)).block).stmts[i], child_ctx);
                }
            }
        }
        if (((*(n)).block).count > 0)
        {
            const Node* last = ((*(n)).block).stmts[((*(n)).block).count - 1];
            if (last != nil && ((*(last)).kind == NODE_RETURN || (*(last)).kind == NODE_BREAK || (*(last)).kind == NODE_CONTINUE))
            {
                early_exit_in_block = true;
            }
        }
        if (!early_exit_in_block)
        {
            (child_ctx).stmt_index = ((*(n)).block).count;
            codegen_dbc_emit_ensures(n, child_ctx);
            codegen_c_emit_defers(n, child_ctx);
        }
    }
    emit_indent((ctx).out, (ctx).indent);
    dynbuf_append((ctx).out, "}\n");
}

/**
 * Generate a separate main(...) wraper for NODE_PROGRAM
 */
static void codegen_c_main_wrapper(const Node* n, CodegenContext ctx)
{
    if (((*(n)).program_decl).return_type != nil)
    {
        emit_return_type((ctx).out, ((*(n)).program_decl).return_type);
        dynbuf_append_char((ctx).out, ' ');
    }
    else
    {
        dynbuf_append((ctx).out, "void ");
    }
    dynbuf_appendn((ctx).out, ((*(n)).program_decl).name, ((*(n)).program_decl).name_len);
    emit_param_list((ctx).out, ((*(n)).program_decl).params, ((*(n)).program_decl).param_count, true, false);
    dynbuf_append_char((ctx).out, '\n');
    if (((*(n)).program_decl).block != nil)
    {
        codegen_c_block(((*(n)).program_decl).block, ctx);
    }
    else
    {
        dynbuf_append((ctx).out, "{\n");
        emit_indent((ctx).out, (ctx).indent + 1);
        dynbuf_append((ctx).out, "/* Empty body */\n");
        dynbuf_append((ctx).out, "}\n");
    }
    dynbuf_append((ctx).out, "\n");
    dynbuf_append((ctx).out, "int main");
    emit_param_list((ctx).out, ((*(n)).program_decl).params, ((*(n)).program_decl).param_count, true, false);
    dynbuf_append_char((ctx).out, '\n');
    dynbuf_append((ctx).out, "{\n");
    emit_indent((ctx).out, (ctx).indent + 1);
    if (((*(n)).program_decl).return_type != nil)
    {
        dynbuf_append((ctx).out, "return ");
    }
    dynbuf_appendn((ctx).out, ((*(n)).program_decl).name, ((*(n)).program_decl).name_len);
    dynbuf_append_char((ctx).out, '(');
    if (((*(n)).program_decl).param_count > 0)
    {
        dynbuf_append((ctx).out, "argc");
    }
    if (((*(n)).program_decl).param_count > 1)
    {
        dynbuf_append((ctx).out, ", argv");
    }
    dynbuf_append((ctx).out, ");\n");
    if (((*(n)).program_decl).return_type == nil)
    {
        emit_indent((ctx).out, 1);
        dynbuf_append((ctx).out, "return 0;\n");
    }
    dynbuf_append((ctx).out, "}\n");
}

/**
 * Generate module entry point using module name, parameters, and block.
 */
static void codegen_c_module(const Node* n, CodegenContext ctx)
{
    if (((*(n)).program_decl).return_type != nil)
    {
        emit_return_type((ctx).out, ((*(n)).program_decl).return_type);
        dynbuf_append_char((ctx).out, ' ');
    }
    else
    {
        dynbuf_append((ctx).out, "void ");
    }
    dynbuf_appendn((ctx).out, ((*(n)).program_decl).name, ((*(n)).program_decl).name_len);
    emit_param_list((ctx).out, ((*(n)).program_decl).params, ((*(n)).program_decl).param_count, true, false);
    dynbuf_append_char((ctx).out, '\n');
    if (((*(n)).program_decl).block != nil)
    {
        codegen_c_block(((*(n)).program_decl).block, ctx);
    }
    else
    {
        dynbuf_append((ctx).out, "{\n");
        emit_indent((ctx).out, (ctx).indent + 1);
        dynbuf_append((ctx).out, "/* Empty body */\n");
        dynbuf_append((ctx).out, "}\n");
    }
}

/**
 * Emit top-level program / module
 */
static void codegen_c_program(const Node* n, CodegenContext ctx)
{
    if (n == nil || (*(n)).kind != NODE_PROGRAM)
    {
        fprintf(stderr, "FATAL ERROR: codegen_c_program: expected NODE_PROGRAM\n");
        exit(1);
    }
    dynbuf_append((ctx).out, "/* =====================================\n");
    dynbuf_append((ctx).out, " * Generated by Mod-c ");
    dynbuf_append((ctx).out, VERSION_BASE);
    dynbuf_append((ctx).out, "\n");
    if (((*(n)).program_decl).unit_kind == TOK_KEYWORD_PROGRAM)
    {
        dynbuf_append((ctx).out, " * PROGRAM ");
    }
    else if (((*(n)).program_decl).unit_kind == TOK_KEYWORD_MODULE)
    {
        dynbuf_append((ctx).out, " * MODULE ");
    }
    else
    {
        dynbuf_append((ctx).out, " * UNKNOWN ");
    }
    dynbuf_appendn((ctx).out, ((*(n)).program_decl).name, ((*(n)).program_decl).name_len);
    dynbuf_append_char((ctx).out, '\n');
    dynbuf_append((ctx).out, " * ===================================== */\n\n");
    dynbuf_append((ctx).out, "#include \"");
    dynbuf_appendn((ctx).out, ((*(n)).program_decl).name, ((*(n)).program_decl).name_len);
    dynbuf_append((ctx).out, ".h\"\n\n");
    if ((ctx).debug_enabled)
    {
        dynbuf_append((ctx).out, "/********** Module Prototype ****************/\n\n");
    }
    if (((*(n)).program_decl).unit_kind == TOK_KEYWORD_MODULE)
    {
        codegen_common_module_prototype(n, ctx);
    }
    if (((*(n)).program_decl).decls != nil)
    {
        size_t i = {0};
        if ((ctx).debug_enabled)
        {
            dynbuf_append((ctx).out, "/********** Top Level Declarations ********/\n\n");
        }
        {
            const long long __for_end_l1095 = (long long)(((*(n)).program_decl).count - 1);
            for (i = 0; (long long)(i) <= __for_end_l1095; i++)
            {
                {
                    const Node* d = ((*(n)).program_decl).decls[i];
                    if ((*(d)).kind == NODE_IMPORT)
                    {
                        codegen_common_import(d, ctx);
                    }
                    else
                    {
                        codegen_c_stmt(d, ctx);
                    }
                }
            }
        }
        dynbuf_append_char((ctx).out, '\n');
    }
    if (((*(n)).program_decl).unit_kind == TOK_KEYWORD_PROGRAM)
    {
        codegen_c_main_wrapper(n, ctx);
    }
    else if (((*(n)).program_decl).unit_kind == TOK_KEYWORD_MODULE)
    {
        if ((ctx).debug_enabled)
        {
            dynbuf_append((ctx).out, "/********** Module Body **********/\n\n");
        }
        codegen_c_module(n, ctx);
    }
}

/**
 * Public entry point: generate C code from AST
 * Writes to the provided DynBuf.
 * Exits on fatal error.
 */

void codegen_c(CodegenContext ctx)
{
    if ((ctx).ast == nil || (ctx).out == nil)
    {
        fprintf(stderr, "FATAL ERROR: codegen_c_ NULL arguments\n");
        exit(1);
    }
    codegen_c_program((ctx).ast, ctx);
}
