/* =====================================
 * Generated by Mod-c 0.26.8
 * HEADER codegen_mh MODULE
 * ===================================== */

#ifndef MODC_MODULE_codegen_mh_H
#define MODC_MODULE_codegen_mh_H

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

#define nil ((void *)0)
#define NIL nil
typedef uint8_t byte;
typedef const char* string;
typedef int integer;
typedef unsigned int cardinal;
typedef float real;

/**
 * codegen_mh.mc - Emit modc-mh/1 symbol export files for EXPORT declarations.
 */

/* === IMPORT === */
#include "dynbuf.h"

/* === IMPORT === */
#include "Lexer.h"

/* === IMPORT === */
#include "ttype.h"

/* === IMPORT === */
#include "stddef.h"

/* === IMPORT === */
#include "stdio.h"

/* === IMPORT === */
#include "stdlib.h"

/* === IMPORT === */
#include "string.h"

/* === IMPORT === */
#include "version.h"

/* === IMPORT === */
#include "node.h"

/* === IMPORT === */
#include "codegen_common.h"

/**
 * Emit MODULE/PROGRAM unit entry (name matches unit; not an EXPORT decl in source).
 * Mirros codegen_common_module_prototype() in generated .h files.
 */

/* === PROC/FUNC EXPORT === */
bool codegen_mh_has_exports(const Node* root);

/**
 * Main entry point for this module, codegen_mh()
 */

void codegen_mh(CodegenContext ctx);

#endif /* MODC_MODULE_codegen_mh_H */
