/* =====================================
 * Generated by Mod-c 0.26.9
 * HEADER codegen_common MODULE
 * ===================================== */

#ifndef MODC_MODULE_codegen_common_H
#define MODC_MODULE_codegen_common_H

#include <stdint.h>
#include <stdbool.h>
#include <assert.h>

#define nil ((void *)0)
#define NIL nil
typedef uint8_t byte;
typedef int integer;
typedef unsigned int cardinal;
typedef float real;

/**
 * CodegenCommon.mc
 * 5 June 2026
 * 
 * Shared code generation helpers used by both the full C emitter (codegen_c.c)
 * and the header emitter (codegen_header.mc).
 * This file should contain only low-level emission primatives and context
 * management that are independent of "full program" vs "header only" logic.
 *
 * 28 August 2026 - Conversion form .c to .mc started
 */

/* === IMPORT === */
#include "tmodc.h"

/* === IMPORT === */
#include "arena.h"

/* === IMPORT === */
#include "dynbuf.h"

/* === IMPORT === */
#include "Lexer.h"

/* === IMPORT === */
#include "mh_reader.h"

/* === IMPORT === */
#include "node.h"

/* === IMPORT === */
#include "stddef.h"

/* === IMPORT === */
#include "stdio.h"

/* === IMPORT === */
#include "string.h"

/* === IMPORT === */
#include "symbol.h"

/* === IMPORT === */
#include "symkind.h"

/* === IMPORT === */
#include "ttype.h"

/* === IMPORT === */
#include "utils.h"

/** ===================================
 *  Codegen Context
 *  ===================================
 */

/**
 * Target backend selection
 */

/* === TYPE EXPORT === */
typedef enum {
    TARGET_C = 0,
    TARGET_HEADER = 1,
    TARGET_MH = 2,
    TARGET_VM = 3,
    TARGET_WASM = 4,
    TARGET_JSON = 5
} CodegenTarget;

/**
 * Context passed through all recursive codegen functions.
 * Contains the output buffer, current indentation, and parent/scope intormation.
 * This eliminates long parameter lists and makes future extensions (symbol table,
 * defer lists, etc.) trivial. This is setup by the main codegen_generate function.
 */

/* === TYPE EXPORT === */
typedef struct CodegenContext CodegenContext;
typedef struct CodegenContext {
    pDynBuf out;
    const Node* ast;
    integer indent;
    bool debug_enabled;
    bool assert_off;
    bool dbc_off;
    CodegenTarget target;
    const CodegenContext* parent_ctx;
    const Node* parent_node;
    const Node* enclosing_func;
    const Node* enclosing_loop;
    size_t stmt_index;
} CodegenContext;

/* === TYPE EXPORT === */
typedef CodegenContext* pCodegenContext;

/**
 * Creae a child context for a nested node.
 */

/* === PROC/FUNC EXPORT === */
CodegenContext ctx_push(const CodegenContext* ctx, const Node* new_parent);

/* === PROC/FUNC EXPORT === */
void emit_indent(pDynBuf out, int indent);

/* === PROC/FUNC EXPORT === */
bool codegen_unit_binds_portable(const Node* prog, const char* name, size_t name_len);

/* === PROC/FUNC EXPORT === */
void codegen_emit_c_prelude(pDynBuf out, const Node* prog);

/* === PROC/FUNC EXPORT === */
void emit_return_type(pDynBuf out, const TType* t);

/* === PROC/FUNC EXPORT === */
void emit_array_type(pDynBuf out, const TType* t, const char* name, size_t name_len);

/* === PROC/FUNC EXPORT === */
void emit_type_specifier(pDynBuf out, const TType* t, const char* name, size_t length, bool is_param, bool is_var, bool is_ref, bool is_const);

/* === PROC/FUNC EXPORT === */
void emit_param_list(pDynBuf out, pNode* params, size_t count, bool is_parameter, bool has_ellipsis);

/* === PROC/FUNC EXPORT === */
void emit_var_decl(pDynBuf out, const char* name, size_t name_len, const TType* t);

/* === PROC/FUNC EXPORT === */
void emit_doc_comment_as_c(pDynBuf out, const Node* n);

/**
 * Emit a LET binding name: name_l{line}_c{col}
 * binding_decl is the NODE_LET_ITEM (sym-decl or let item node).
 */

/* === PROC/FUNC EXPORT === */
void emit_let_binding_name(pDynBuf out, const char* name, size_t name_len, const Node* binding_decl);

/**
 * Emit an identifier expression (mangles LET uses via resolved_sym).
 */

/* === PROC/FUNC EXPORT === */
void emit_let_ident(pDynBuf out, const Node* n);

/* === PROC/FUNC EXPORT === */
void codegen_common_type_decl(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_proc_or_func(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_struct_decl(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_union_decl(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_enum_type(const Node* n, const char* type_name, size_t type_name_len, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_method_type(const Node* method, const Node* type_decl, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_expr(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_emit_literal(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_array_literal(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_preprocessor(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_field_access(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_sizeof_expr(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_countof_expr(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_inc_dec(const Node* n, CodegenContext ctx, bool as_statement);

/* === PROC/FUNC EXPORT === */
void codegen_common_module_prototype(const Node* n, CodegenContext ctx);

/* === PROC/FUNC EXPORT === */
void codegen_common_import(const Node* n, CodegenContext ctx);

/**
 * Create a child context for a nested node.
 * Struct copy is cheap and safe.
 * Exits on fatal error (should never happen in normal use.).
 */

/* === PROC/FUNC EXPORT === */
CodegenContext ctx_push(const CodegenContext* ctx, const Node* new_parent);

/**
 * Emit indentation (4 spaces per level)
 * Safe, clear, and silences -Wstrict-overflow without complexity.
 */

/* === PROC/FUNC EXPORT === */
void emit_indent(pDynBuf out, int indent);

/**
 * Emit Doc Comment, both Pascal and C style as C style comments.
 */

/* === PROC/FUNC EXPORT === */
void emit_doc_comment_as_c(pDynBuf out, const Node* n);

/**
 * True if this unit has type Name = ... for a portable rebindable name.
 */

/* === PROC/FUNC EXPORT === */
bool codegen_unit_binds_portable(const Node* prog, const char* name, size_t name_len);

/**
 * C ABI prelude for a generated .h (includes, nil, byte, portable four).
 * Unit TYPE binds replace the default typedef for that name.
 */

/* === PROC/FUNC EXPORT === */
void codegen_emit_c_prelude(pDynBuf out, const Node* prog);

/**
 * Emit return type. Same as type-specifier except [] not allowed.
 * TODO: fill out code for handling array type returns, i.e. they must collapse into just *
 */

/* === PROC/FUNC EXPORT === */
void emit_return_type(pDynBuf out, const TType* t);

/**
 * Emit C array type syntax for typedefs and declarations.
 * Recursively handles nested arrays and the ARRAY[N] of syntax.
 * Produces correct C syntax, for example: int Matrix[4][4] or int Vector3[3]
 *
 * Called with name = nil when emitting only the base type (inner recursion).
 */

/* === PROC/FUNC EXPORT === */
void emit_array_type(pDynBuf out, const TType* t, const char* name, size_t name_len);

/**
 * Emit type specifier (for typedef, function returns, parameters, etc.)
 * Supports: normal types, open arrays T[], fixed arrays T[N]. If type is an array
 * it needs the name of an identifier associated with the type as array information
 * will be declared after the identifer name. If name = nil or len = 0, then array
 * information will collaps into just a '*' after the type name.
 * New Parameter Passing Model:
 *  - VAR   -> T*
 *  - REF   -> T*
 *  - CONST -> const T* (or const T for small types)
 *  - default -> T (or const T* for aggregates)
 *
 * @param out = output buffer
 * @param t = TType to generate code for
 * @param name = name of the identifier associated with type. Needed for arrays
 * @param len = length of the name.
 */

/* === PROC/FUNC EXPORT === */
void emit_type_specifier(pDynBuf out, const TType* t, const char* name, size_t length, bool is_param, bool is_var, bool is_ref, bool is_const);

/**
 * Emit parameter list
 */

/* === PROC/FUNC EXPORT === */
void emit_param_list(pDynBuf out, pNode* params, size_t count, bool is_parameter, bool has_ellipsis);

/** 
 * Emit a full variable declaration (name + array brackets in correct position)
 * Example bool is_prime[101] = {0}
 */

/* === PROC/FUNC EXPORT === */
void emit_var_decl(pDynBuf out, const char* name, size_t name_len, const TType* t);

/**
 * Emit a LET binding name: name_l{line}_c{col}
 * binding_decl is the NODE_LET_ITEM (sym-decl or let item node).
 */

/* === PROC/FUNC EXPORT === */
void emit_let_binding_name(pDynBuf out, const char* name, size_t name_len, const Node* binding_decl);

/**
 * Codegen_param_is_by_ref
 */

/**
 * True when C formal is T* alias of value T (not when formal type is already ^U).
 */

/**
 * Formal for call arg index (0-based). Instance sugar: receiver is formal 0,
 * so args[i] maps to formals[i + 1].
 */

/**
 * codgen_call_formal_receiver
 */

/**
 * True when this actual should be emitted with a leading '&' for a VAR/REF formal
 */

/**
 * codegen_emit_call_arg_deref
 */

/**
 * Emit an identifier expression (mangles LET uses via resolved_sym).
 */

/* === PROC/FUNC EXPORT === */
void emit_let_ident(pDynBuf out, const Node* n);

/**
 * Emit a TYPE declaration.
 * Simple types for now.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_type_decl(const Node* n, CodegenContext ctx);

/**
 * Emit Declaration portion of PROCEDURE or FUNCTION.
 * To be called by codegen_c or codegen_header.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_proc_or_func(const Node* n, CodegenContext ctx);

/**
 * Emit STRUCT declaration.
 * Maps to a C typedef struct with named fields.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_struct_decl(const Node* n, CodegenContext ctx);

/**
 * Emit UNION declaration. (Uses NODE_STRUCT_DECL)
 * Maps to a C typedef union with named field.s
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_union_decl(const Node* n, CodegenContext ctx);

/**
 * Emit ENUM type body for TYPE T = ENUM ... END.
 * Emits: enum { M = n, ... } TypeName
 * (Caller adds 'typedf' and trailing ';')
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_enum_type(const Node* en, const char* type_name, size_t type_name_len, CodegenContext ctx);

/**
 * Generate method type.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_method_type(const Node* method, const Node* type_decl, CodegenContext ctx);

/**
 * Emit expression
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_expr(const Node* n, CodegenContext ctx);

/**
 * Emit a literal value as C11-compatible source text.
 *  -   Decimal, hex (0x), octal (converted from 0o to 0), binary
 *      converted from 0b to octal or decimal.
 *  -   Strips all '_' separators.
 *  -   Preserves original token text for strings and chars.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_emit_literal(const Node* n, CodegenContext ctx);

/** 
 * Emit array literal: { expr, expr, ... }
 * Special fast path for the extremly common {0} zero-initializer.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_array_literal(const Node* n, CodegenContext ctx);

/**
 * Preprocessor directives.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_preprocessor(const Node* n, CodegenContext ctx);

/**
 * Emit define
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_define(const Node* n, CodegenContext ctx);

/**
 * Emit field access: record.field
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_field_access(const Node* n, CodegenContext ctx);

/**
 * Emit COUNTOF. Semantic stores the outermost bound in count.
 * ((integer)N)
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_countof_expr(const Node* n, CodegenContext ctx);

/**
 * Emit SIZEOF (type or designator)
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_sizeof_expr(const Node* n, CodegenContext ctx);

/**
 * Emit INC / DEC statement (works for both statements and expressions)
 *
 * Statement context:   INC(x)      => x++
 *                      INC(x, 5)   => x += 5
 *
 * Expression context:  INC(x)      => x++
 *                      INC(x, 5)   => (x += 5)     <<-- parentheses added here
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_inc_dec(const Node* n, CodegenContext ctx, bool as_statement);

/**
 * Write out module prototype.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_module_prototype(const Node* n, CodegenContext ctx);

/**
 * Emit a C #include from IMPORT ... FROM "path"
 * The string-literal token includes quotes.
 * .mh paths: emit the associated .h (same step/path); tmodc reads .mh at compile time only.
 */

/* === PROC/FUNC EXPORT === */
void codegen_common_import(const Node* n, CodegenContext ctx);

void codegen_common(void);

#endif /* MODC_MODULE_codegen_common_H */
