/* =====================================
 * Generated by Mod-c 0.26.8
 * MODULE mh_exportkind
 * ===================================== */

#include "mh_exportkind.h"

void mh_exportkind(void);

/**
 * mh_exportkind
 */

void mh_exportkind(void)
{
}
