/* =====================================
 * Generated by Mod-c 0.26.8
 * MODULE symkind
 * ===================================== */

#include "symkind.h"

void symkind(void);

/**
 * symkind.mc - Symbol classification for semantic analysis.
 * Hand-maintained until Mod-C ENUM syntax can own this definition.
 * Port target: export type SymbolKind = enum ... end in tsymbol.mc (or symkind.mc)
 */

void symkind(void)
{
}
